[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=365000000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self' http://*.addthis.com; img-src 'self' https://upload.wikimedia.org data:; connect-src 'self' https://cloudflareinsights.com http://*.addthis.com; script-src 'self' https://static.cloudflareinsights.com http://*.addthis.com https://*.addthisedge.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
